"""  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TL;DR  -->  install delegating git hook wrappers so local hooks stay aligned
            with the current repo-owned hook files

- Later Extension Points:
    --> add narrower install filtering only if hook families split further later

- Role:
    --> writes wrapper hooks into `.git/hooks` instead of copying hook bodies
    --> preserves executable permissions for the installed local hook scripts

- Exports:
    --> `main()`

- Consumed By:
    --> local operators running `bun run hooks:install`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  """

from __future__ import annotations

import stat
from pathlib import Path

WRAPPER_MARKER = "# Generated by tools/install_hooks.py."
LEGACY_COPY_SIGNATURES = (
    "TL;DR  -->",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    "local git hook execution after `python3 tools/install_hooks.py`",
)
WRAPPER_TEMPLATE = "\n".join(
    (
        "#!/bin/sh",
        WRAPPER_MARKER,
        "# Delegates to the current repo-owned hook so hook updates apply without reinstall.",
        "",
        "set -eu",
        "",
        'repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)',
        'exec "$repo_root/tools/hooks/{hook_name}" "$@"',
        "",
    )
)


def _build_wrapper(hook_name: str) -> str:
    return WRAPPER_TEMPLATE.format(hook_name=hook_name)


def _is_repo_wrapper(path: Path) -> bool:
    if not path.is_file():
        return False
    try:
        content = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return False
    if WRAPPER_MARKER not in content:
        return False
    return 'exec "$repo_root/tools/hooks/' in content


def _is_legacy_repo_hook_copy(path: Path) -> bool:
    if not path.is_file():
        return False
    try:
        content = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return False
    if WRAPPER_MARKER in content:
        return False
    return all(signature in content for signature in LEGACY_COPY_SIGNATURES)


def _remove_stale_wrappers(hooks_dir: Path, expected_names: set[str]) -> None:
    for installed_path in sorted(hooks_dir.iterdir()):
        if installed_path.name in expected_names:
            continue
        if not _is_repo_wrapper(installed_path) and not _is_legacy_repo_hook_copy(
            installed_path
        ):
            continue
        installed_path.unlink()


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    hooks_dir = repo_root / ".git" / "hooks"
    source_dir = repo_root / "tools" / "hooks"
    source_paths = sorted(path for path in source_dir.iterdir() if path.is_file())
    hook_names = {path.name for path in source_paths}

    hooks_dir.mkdir(parents=True, exist_ok=True)
    _remove_stale_wrappers(hooks_dir, hook_names)
    for path in source_paths:
        target_path = hooks_dir / path.name
        target_path.write_text(_build_wrapper(path.name), encoding="utf-8")
        target_path.chmod(target_path.stat().st_mode | stat.S_IXUSR)

    print("Git hooks installed from tools/hooks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
